from __future__ import annotations

import json
from copy import deepcopy
from pathlib import Path
import sys
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from scoring.ambiguity import (
    ambiguity_result_to_schema_payload,
    label_ambiguity_from_hypotheses,
)
from scoring.experiment_utility import (
    experiment_ranking_to_oracle_payload,
    rank_candidate_experiments,
)
from simulators.damped_oscillator import (
    hypothesis_from_model_payload,
    simulate_trajectory,
)


OUTPUT_DIR = Path("generated_scenarios")


def main() -> int:
    OUTPUT_DIR.mkdir(exist_ok=True)

    scenario_specs = [
        _nonlinear_vs_linear_short_window_spec(),
        _linear_vs_driven_short_window_spec(),
    ]

    written_files = []
    for spec in scenario_specs:
        scenario = build_scenario(spec)
        output_path = OUTPUT_DIR / f"{scenario['scenario_id']}.json"
        output_path.write_text(json.dumps(scenario, indent=2), encoding="utf-8")
        written_files.append(output_path)

    print(f"generated {len(written_files)} scenario file(s)")
    for path in written_files:
        print(path.as_posix())
    return 0


def build_scenario(spec: dict[str, Any]) -> dict[str, Any]:
    true_hypothesis = spec["true_hypothesis"]
    baseline_condition = deepcopy(spec["baseline_condition"])
    baseline_initial_state = deepcopy(baseline_condition["initial_state"])

    observation_episode = _generate_observation_episode(
        episode_id="obs_1",
        condition_id=baseline_condition["condition_id"],
        hypothesis=true_hypothesis,
        condition=baseline_condition,
    )

    hypotheses = [
        _build_hypothesis_entry(item)
        for item in spec["candidate_hypotheses"]
    ]

    ambiguity_result = label_ambiguity_from_hypotheses(
        hypotheses=hypotheses,
        observation_episode=observation_episode,
        initial_state=baseline_initial_state,
        score_type="mse",
        max_score_gap=spec["ambiguity_rule"]["max_score_gap"],
        ambiguity_type=spec["ambiguity_rule"]["ambiguity_type"],
    )

    name_to_id = {hypothesis["name"]: hypothesis["hypothesis_id"] for hypothesis in hypotheses}
    ambiguity_payload = ambiguity_result_to_schema_payload(
        ambiguity_result,
        hypothesis_name_to_id=name_to_id,
    )

    candidate_experiments = deepcopy(spec["candidate_experiments"])
    compatible_hypotheses = [
        hypothesis
        for hypothesis in hypotheses
        if hypothesis["name"] in ambiguity_result.compatible_hypotheses
    ]

    experiment_ranking = rank_candidate_experiments(
        candidate_experiments=candidate_experiments,
        compatible_hypotheses=compatible_hypotheses,
        baseline_initial_state=baseline_initial_state,
    )
    oracle_payload = experiment_ranking_to_oracle_payload(
        experiment_ranking,
        true_hypothesis_id=spec["true_hypothesis"]["hypothesis_id"],
        explanation=(
            "Generated by the oscillator backend oracle using pairwise disagreement "
            "over simulated candidate experiment responses."
        ),
    )

    return {
        "schema_version": "0.1",
        "scenario_id": spec["scenario_id"],
        "domain": "damped_oscillator",
        "goal": deepcopy(spec["goal"]),
        "observations": {
            "episodes": [observation_episode],
            "observability": deepcopy(spec["observability"]),
        },
        "hypotheses": hypotheses,
        "candidate_experiments": candidate_experiments,
        "ambiguity_assessment": ambiguity_payload,
        "ground_truth": oracle_payload,
        "metadata": deepcopy(spec["metadata"]),
    }


def _generate_observation_episode(
    *,
    episode_id: str,
    condition_id: str,
    hypothesis: dict[str, Any],
    condition: dict[str, Any],
) -> dict[str, Any]:
    simulator_hypothesis = hypothesis_from_model_payload(hypothesis["model"])
    trace = simulate_trajectory(
        hypothesis=simulator_hypothesis,
        condition=_simulator_condition_from_config(condition),
    )

    return {
        "episode_id": episode_id,
        "condition_id": condition_id,
        "measured_channels": list(condition["measured_channels"]),
        "time": trace.time,
        "values": trace.channels,
        "noise_model": {
            "type": "none",
            "parameters": {},
        },
        "summary_stats": {
            "window_duration": condition["duration"],
            "sampling_rate": condition["sampling_rate"],
        },
    }


def _build_hypothesis_entry(spec: dict[str, Any]) -> dict[str, Any]:
    return {
        "hypothesis_id": spec["hypothesis_id"],
        "name": spec["name"],
        "description": spec["description"],
        "family": "ode",
        "mechanism_tags": list(spec["mechanism_tags"]),
        "model": deepcopy(spec["model"]),
    }


def _simulator_condition_from_config(condition: dict[str, Any]):
    from simulators.damped_oscillator import (
        OscillatorExperimentCondition,
        OscillatorInitialState,
    )

    return OscillatorExperimentCondition(
        duration=float(condition["duration"]),
        time_step=1.0 / float(condition["sampling_rate"]),
        initial_state=OscillatorInitialState(
            x=float(condition["initial_state"]["x"]),
            v=float(condition["initial_state"]["v"]),
        ),
        measured_channels=tuple(condition["measured_channels"]),
    )


def _common_goal() -> dict[str, Any]:
    return {
        "type": "distinguish_hypotheses",
        "description": "Determine which mechanism best explains the current damped-oscillator observations.",
        "success_criterion": "Choose the candidate experiment expected to produce the largest separation between the remaining plausible hypotheses.",
    }


def _common_candidate_experiments() -> list[dict[str, Any]]:
    experiments = [
        _window_experiment("E1", end_time=1.0, sampling_rate=10.0, baseline_end_time=0.5, cost=1.0),
        _window_experiment("E2", end_time=2.0, sampling_rate=10.0, baseline_end_time=0.5, cost=1.2),
        _window_experiment("E3", end_time=3.0, sampling_rate=10.0, baseline_end_time=0.5, cost=1.4),
        _sampling_experiment("E4", sampling_rate=20.0, baseline_sampling_rate=10.0, cost=1.0),
        _sampling_experiment("E5", sampling_rate=50.0, baseline_sampling_rate=10.0, cost=1.2),
        _sampling_experiment("E6", sampling_rate=100.0, baseline_sampling_rate=10.0, cost=1.4),
        _velocity_channel_experiment("E7", duration=0.5, sampling_rate=10.0, baseline_end_time=0.5, cost=1.5),
        _velocity_channel_experiment("E8", duration=1.0, sampling_rate=10.0, baseline_end_time=0.5, cost=1.8),
        _initial_velocity_experiment(
            "E9",
            initial_velocity=0.75,
            reference_initial_velocity=0.75,
            duration=1.0,
            baseline_end_time=0.5,
            cost=1.2,
        ),
        _initial_velocity_experiment(
            "E10",
            initial_velocity=1.5,
            reference_initial_velocity=0.75,
            duration=1.0,
            baseline_end_time=0.5,
            cost=1.5,
        ),
    ]
    return experiments


def _window_experiment(
    experiment_id: str,
    *,
    end_time: float,
    sampling_rate: float,
    baseline_end_time: float,
    cost: float,
) -> dict[str, Any]:
    window_ratio = end_time / baseline_end_time
    return {
        "experiment_id": experiment_id,
        "name": f"extend_window_by_{_format_ratio_token(window_ratio)}x",
        "description": (
            f"Measure position over a window {window_ratio:.1f}x the baseline duration using the same initial condition."
        ),
        "intervention_type": "measurement_change",
        "changes": {
            "time_window": {"start": 0.0, "end": end_time},
        },
        "measurement_plan": {
            "channels": ["x"],
            "sampling_rate": sampling_rate,
            "time_window": {"start": 0.0, "end": end_time},
            "metadata": {
                "experiment_family": "extend_observation_window",
                "parameterization": {
                    "window_ratio": window_ratio,
                    "baseline_end_time": baseline_end_time,
                    "end_time": end_time,
                },
            },
        },
        "ambiguity_tags": ["short_window"],
        "cost": cost,
        "metadata": {
            "experiment_family": "extend_observation_window",
            "parameterization": {
                "window_ratio": window_ratio,
                "baseline_end_time": baseline_end_time,
                "end_time": end_time,
                "sampling_rate": sampling_rate,
            },
        },
    }


def _sampling_experiment(
    experiment_id: str,
    *,
    sampling_rate: float,
    baseline_sampling_rate: float,
    cost: float,
) -> dict[str, Any]:
    sampling_ratio = sampling_rate / baseline_sampling_rate
    return {
        "experiment_id": experiment_id,
        "name": f"increase_sampling_rate_by_{_format_ratio_token(sampling_ratio)}x",
        "description": (
            f"Measure position over the baseline window at {sampling_ratio:.1f}x the baseline sampling rate."
        ),
        "intervention_type": "measurement_change",
        "changes": {"sampling_rate": sampling_rate},
        "measurement_plan": {
            "channels": ["x"],
            "sampling_rate": sampling_rate,
            "time_window": {"start": 0.0, "end": 0.5},
            "metadata": {
                "experiment_family": "increase_sampling_rate",
                "parameterization": {
                    "sampling_rate_ratio": sampling_ratio,
                    "baseline_sampling_rate": baseline_sampling_rate,
                    "sampling_rate": sampling_rate,
                },
            },
        },
        "ambiguity_tags": ["low_resolution"],
        "cost": cost,
        "metadata": {
            "experiment_family": "increase_sampling_rate",
            "parameterization": {
                "sampling_rate_ratio": sampling_ratio,
                "baseline_sampling_rate": baseline_sampling_rate,
                "sampling_rate": sampling_rate,
            },
        },
    }


def _velocity_channel_experiment(
    experiment_id: str,
    *,
    duration: float,
    sampling_rate: float,
    baseline_end_time: float,
    cost: float,
) -> dict[str, Any]:
    window_ratio = duration / baseline_end_time
    return {
        "experiment_id": experiment_id,
        "name": f"measure_velocity_window_by_{_format_ratio_token(window_ratio)}x",
        "description": (
            f"Measure velocity together with position over a window {window_ratio:.1f}x the baseline duration."
        ),
        "intervention_type": "measurement_change",
        "changes": {"add_channels": ["v"]},
        "measurement_plan": {
            "channels": ["x", "v"],
            "sampling_rate": sampling_rate,
            "time_window": {"start": 0.0, "end": duration},
            "metadata": {
                "experiment_family": "measure_velocity_channel",
                "parameterization": {
                    "window_ratio": window_ratio,
                    "baseline_end_time": baseline_end_time,
                    "duration": duration,
                    "sampling_rate": sampling_rate,
                },
            },
        },
        "ambiguity_tags": ["hidden_variable"],
        "cost": cost,
        "metadata": {
            "experiment_family": "measure_velocity_channel",
            "parameterization": {
                "window_ratio": window_ratio,
                "baseline_end_time": baseline_end_time,
                "duration": duration,
                "sampling_rate": sampling_rate,
            },
        },
    }


def _initial_velocity_experiment(
    experiment_id: str,
    *,
    initial_velocity: float,
    reference_initial_velocity: float,
    duration: float,
    baseline_end_time: float,
    cost: float,
) -> dict[str, Any]:
    velocity_ratio = initial_velocity / reference_initial_velocity
    window_ratio = duration / baseline_end_time
    return {
        "experiment_id": experiment_id,
        "name": f"increase_initial_velocity_by_{_format_ratio_token(velocity_ratio)}x_ref",
        "description": (
            f"Repeat the run with initial velocity {velocity_ratio:.1f}x a reference excitation scale and observe position over {window_ratio:.1f}x the baseline duration."
        ),
        "intervention_type": "initial_condition_change",
        "changes": {
            "initial_state": {"x": 1.0, "v": initial_velocity},
        },
        "measurement_plan": {
            "channels": ["x"],
            "sampling_rate": 10.0,
            "time_window": {"start": 0.0, "end": duration},
            "metadata": {
                "experiment_family": "increase_initial_velocity",
                "parameterization": {
                    "initial_velocity_ratio": velocity_ratio,
                    "reference_initial_velocity": reference_initial_velocity,
                    "initial_velocity": initial_velocity,
                    "window_ratio": window_ratio,
                    "baseline_end_time": baseline_end_time,
                    "duration": duration,
                },
            },
        },
        "ambiguity_tags": ["weak_excitation"],
        "cost": cost,
        "metadata": {
            "experiment_family": "increase_initial_velocity",
            "parameterization": {
                "initial_velocity_ratio": velocity_ratio,
                "reference_initial_velocity": reference_initial_velocity,
                "initial_velocity": initial_velocity,
                "window_ratio": window_ratio,
                "baseline_end_time": baseline_end_time,
                "duration": duration,
            },
        },
    }


def _format_numeric_token(value: float) -> str:
    if float(value).is_integer():
        return str(int(value))
    return str(value).replace(".", "p")


def _format_ratio_token(value: float) -> str:
    return _format_numeric_token(value)


def _nonlinear_vs_linear_short_window_spec() -> dict[str, Any]:
    return {
        "scenario_id": "generated_osc_nonlinear_vs_linear_001",
        "goal": _common_goal(),
        "baseline_condition": {
            "condition_id": "baseline_short_window",
            "duration": 0.5,
            "sampling_rate": 10.0,
            "initial_state": {"x": 1.0, "v": 0.0},
            "measured_channels": ["x"],
        },
        "observability": {
            "available_channels": ["x"],
            "hidden_channels": ["v"],
            "notes": "Baseline observation uses a short, position-only window.",
        },
        "true_hypothesis": {
            "hypothesis_id": "H2",
            "name": "weak_nonlinear_damping",
            "description": "A damped oscillator with velocity-dependent nonlinear damping.",
            "mechanism_tags": ["nonlinear_damping"],
            "model": {
                "state_variables": ["x", "v"],
                "observed_variables": ["x"],
                "parameters": {"m": 1.0, "c1": 0.24, "c2": 0.08, "k": 2.0},
                "equations": {
                    "type": "symbolic_ode",
                    "state_order": ["x", "v"],
                    "rhs": [
                        "v",
                        "(-(c1 + c2 * abs(v)) * v - k * x) / m",
                    ],
                },
            },
        },
        "candidate_hypotheses": [
            {
                "hypothesis_id": "H1",
                "name": "linear_damping",
                "description": "A damped oscillator with linear viscous damping.",
                "mechanism_tags": ["linear_damping"],
                "model": {
                    "state_variables": ["x", "v"],
                    "observed_variables": ["x"],
                    "parameters": {"m": 1.0, "c": 0.3, "k": 2.0},
                    "equations": {
                        "type": "symbolic_ode",
                        "state_order": ["x", "v"],
                        "rhs": ["v", "(-c * v - k * x) / m"],
                    },
                },
            },
            {
                "hypothesis_id": "H2",
                "name": "weak_nonlinear_damping",
                "description": "A damped oscillator with velocity-dependent nonlinear damping.",
                "mechanism_tags": ["nonlinear_damping"],
                "model": {
                    "state_variables": ["x", "v"],
                    "observed_variables": ["x"],
                    "parameters": {"m": 1.0, "c1": 0.24, "c2": 0.08, "k": 2.0},
                    "equations": {
                        "type": "symbolic_ode",
                        "state_order": ["x", "v"],
                        "rhs": [
                            "v",
                            "(-(c1 + c2 * abs(v)) * v - k * x) / m",
                        ],
                    },
                },
            },
        ],
        "candidate_experiments": _common_candidate_experiments(),
        "ambiguity_rule": {
            "max_score_gap": 0.01,
            "ambiguity_type": "short_window",
        },
        "metadata": {
            "generator": "build_oscillator_scenarios.py",
            "seed": 0,
            "difficulty": "medium",
            "source": "programmatic",
            "notes": "Generated short-window ambiguity scenario for nonlinear vs linear damping.",
        },
    }


def _linear_vs_driven_short_window_spec() -> dict[str, Any]:
    return {
        "scenario_id": "generated_osc_linear_vs_driven_001",
        "goal": _common_goal(),
        "baseline_condition": {
            "condition_id": "baseline_short_window",
            "duration": 0.5,
            "sampling_rate": 10.0,
            "initial_state": {"x": 1.0, "v": 0.0},
            "measured_channels": ["x"],
        },
        "observability": {
            "available_channels": ["x"],
            "hidden_channels": ["v"],
            "notes": "Baseline observation uses a short, position-only window.",
        },
        "true_hypothesis": {
            "hypothesis_id": "H2",
            "name": "weak_external_drive",
            "description": "A damped oscillator with a weak sinusoidal external drive.",
            "mechanism_tags": ["external_drive"],
            "model": {
                "state_variables": ["x", "v"],
                "observed_variables": ["x"],
                "parameters": {
                    "m": 1.0,
                    "c": 0.3,
                    "k": 2.0,
                    "A": 0.03,
                    "omega": 1.8,
                },
                "equations": {
                    "type": "symbolic_ode",
                    "state_order": ["x", "v"],
                    "rhs": [
                        "v",
                        "(-c * v - k * x + A * cos(omega * t)) / m",
                    ],
                },
            },
        },
        "candidate_hypotheses": [
            {
                "hypothesis_id": "H1",
                "name": "linear_damping",
                "description": "A damped oscillator with linear viscous damping and no external drive.",
                "mechanism_tags": ["linear_damping"],
                "model": {
                    "state_variables": ["x", "v"],
                    "observed_variables": ["x"],
                    "parameters": {"m": 1.0, "c": 0.3, "k": 2.0},
                    "equations": {
                        "type": "symbolic_ode",
                        "state_order": ["x", "v"],
                        "rhs": ["v", "(-c * v - k * x) / m"],
                    },
                },
            },
            {
                "hypothesis_id": "H2",
                "name": "weak_external_drive",
                "description": "A damped oscillator with a weak sinusoidal external drive.",
                "mechanism_tags": ["external_drive"],
                "model": {
                    "state_variables": ["x", "v"],
                    "observed_variables": ["x"],
                    "parameters": {
                        "m": 1.0,
                        "c": 0.3,
                        "k": 2.0,
                        "A": 0.03,
                        "omega": 1.8,
                    },
                    "equations": {
                        "type": "symbolic_ode",
                        "state_order": ["x", "v"],
                        "rhs": [
                            "v",
                            "(-c * v - k * x + A * cos(omega * t)) / m",
                        ],
                    },
                },
            },
        ],
        "candidate_experiments": _common_candidate_experiments(),
        "ambiguity_rule": {
            "max_score_gap": 0.01,
            "ambiguity_type": "short_window",
        },
        "metadata": {
            "generator": "build_oscillator_scenarios.py",
            "seed": 1,
            "difficulty": "medium",
            "source": "programmatic",
            "notes": "Generated short-window ambiguity scenario for linear damping vs weak external drive.",
        },
    }


if __name__ == "__main__":
    raise SystemExit(main())
